### ISSUE TITLE
2070: Museum of Contemporary Art San Diego

### ISSUE THREAD

**Issue by Blackbaud-KevinDuckworth** [Blackbaud-KevinDuckworth/services-projects#5]
# Client Information
[Altru Credentials](https://blackbaud.my.salesforce.com/0020V00000JjShp)
[Reference URL](https://www.mcasd.org/visit/hours-admissions)
### What you need
- [x] Altru CSS Assets (download from this repository)

## General
- [x] Style sign in modal, if not turned on check user registrtion settings 
- [x] upload image for X in sign-in modal
- [x] Fonts (Helvetica)
- [x] Brand Color applied to buttons
- [x] Site responds on mobile devices

## Header
- [x] Header
   * [x] Logo linked to main site
   * [x] Back to home linked to main site
   * [x] Register and sign-in styles
   * [ ] Is Shopping Cart in scope and was it added

## Footer
- [x] Footer
   * [x] All links are correctly connected

### Altru Pages
- [x] [Register](https://2070a.blackbaudhosting.com/2070a/page.aspx?pid=218)
- [x] [Admission](http://2070a.blackbaudhosting.com/2070a/tickets?tab=3&txobjid=1b87ef14-b89d-4a5c-803f-79124cc2bcd8)

### QA
- [x] Assign to QA 
---

## Quality Assurance Section
- [x] Header and footer are visually accurate compared to client's replication site
- [x] Logo is linked to client's main site
- [x] "Back to Home" button is linked correctly
- [x] Sign-in modal is styled to match client's branding
- [x] Close "x" image has been uploaded to sign-in modal
- [x] Payment screen styled
- [x] Complete Payment button is not cut off on mobile

### Cross-Browser Testing (latest version)
- [x] IE
- [ ] Edge
- [x] Chrome
- [x] Safari
- [x] Firefox

### Responsive Testing
- [x] Tablet Portrait and Landscape
- [x] Phone Portrait and Landscape

### Forms 
- [x] Donation
- [x] Program
- [ ] Combination
- [ ] Membership
- [ ] Event Registration
- [ ] Privacy Policy
- [x] Forgotten User Password
- [x] New user registration

### Add-ons
- [ ] Full Main Navigation
- [ ] Shopping Buttons
- [ ] Email Stationary

**Comment by Blackbaud-KevinDuckworth** [comment]
Hey @Blackbaud-RandeeCampbell, this project is ready to be QA'd.  I wanted to send you a quick message to see if you get this.  I would still like to go through this together on our call on Friday.  

Thanks

**Comment by Blackbaud-RandeeCampbell** [comment]
In progress now.

**Comment by Blackbaud-RandeeCampbell** [comment]
Forgotten Password form buttons stacked on top of each other, add margin. 
![screen shot 2018-06-15 at 3 18 46 pm](https://user-images.githubusercontent.com/5314308/41485694-94490f36-70af-11e8-8501-3aed36c3e7d0.png)

**Comment by Blackbaud-RandeeCampbell** [comment]
No resubmission needed just add a few pixels of margin on the "submit" "log out" buttons on the forgotten password form.

**Comment by Blackbaud-KevinDuckworth** [comment]
This has been updated.  If you agree the QA is complete i will close
